name: Publish

on: workflow_dispatch

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - name: Configure CI Git User
        run: |
          git config user.name "github-actions";
          git config user.email "github-actions@github.com";

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: "github-actions"
          git-user-email: "github-actions@github.com"
          tag-prefix: ''
          output-file: 'CHANGELOG.md'

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.tag }}

      - name: Update package
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          npm i --package-lock-only
          git add .
          git commit --amend -m "ci(release): ${{ steps.changelog.outputs.tag }}"
          git push -f
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
