name: Publish

on: workflow_dispatch

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - name: Configure CI Git User
        run: |
          git config user.name "github-actions";
          git config user.email "github-actions@github.com";

      - name: install
        run: yarn install --immutable

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: "github-actions"
          git-user-email: "github-actions@github.com"
          tag-prefix: ''
          output-file: 'false'

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          fallback-version: '1.0.0'

      - name: Update package
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          yarn install --immutable
          git add .
          git commit -m "chore(package): ${{ steps.changelog.outputs.tag }}"
          git push
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: yarn npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
